steps:
  # Build webexchange image
  - name: gcr.io/cloud_builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/webexchange:$COMMIT_SHA
      - -f
      - WEB_currency_exchange/Dockerfile
      - .

  # Push webexchange image to Google Cloud Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/webexchange:$COMMIT_SHA

  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - --filename=WEB_currency_exchange/deployment.yml
      - --image=gcr.io/$PROJECT_ID/webexchange:$COMMIT_SHA
      - --location=us-central1-c
      - --cluster=forexdemo-cluster