steps:
  # Build webexchange image
  - name: gcr.io/cloud_builders/docker
    args:
      - build
      - -t
      - $_FULL_IMAGENAME
      - -f
      - WEB_currency_exchange/Dockerfile
      - .

  # Push webexchange image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_FULL_IMAGENAME

  # Deploy image to cluster
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - --filename=WEB_currency_exchange/deployment.yml
      - --image=$_FULL_IMAGENAME
      - --location=us-central1-c
      - --cluster=forexdemo-cluster

substitutions:
  _FULL_IMAGENAME    : us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_DOCKER_IMAGENAME}:${SHORT_SHA}
  _ARTIFACT_REGISTRY : forex-docker-repo
  _DOCKER_IMAGENAME  : webexchange