apiVersion: apps/v1
kind: Deployment
metadata:
  name: webexchange
  labels:
    app: webexchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webexchange
  template:
    metadata:
      labels:
        app: webexchange
    spec:
      containers:
        - name: webexchange
          image: us-central1-docker.pkg.dev/titanium-deck-347513/forex-docker-repo/webexchange@[DIGEST]
          ports:
            - containerPort: 80
          env:
            - name: EUREKA_HOST
              value: eureka
            - name: EUREKA_PORT
              value: "8761"
            - name: CURRENCYEXCHANGE_HOST
              value: currencyexchange
            - name: CURRENCYEXCHANGE_PORT
              value: "8100"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyexchange
  labels:
    app: currencyexchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyexchange
  template:
    metadata:
      labels:
        app: currencyexchange
    spec:
      containers:
        - name: currencyexchange
          image: us-central1-docker.pkg.dev/titanium-deck-347513/forex-docker-repo/currencyexchange@[DIGEST]
          ports:
            - containerPort: 8100
          env:
            - name: EUREKA_HOST
              value: eureka
            - name: EUREKA_PORT
              value: "8761"
            - name: FOREX_HOST
              value: forex
            - name: FOREX_PORT
              value: "8000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex
  labels:
    app: forex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forex
  template:
    metadata:
      labels:
        app: forex
    spec:
      containers:
        - name: forex
          image: us-central1-docker.pkg.dev/titanium-deck-347513/forex-docker-repo/forex@[DIGEST]
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password



