apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      run: eureka
  template:
    metadata:
      labels:
        run: eureka
    spec:
      containers:
        - name: eureka
          image: zxpool/eureka:1
          ports:
            - containerPort: 8761



