server:
  port: 8000

eureka:
  client:
    enabled: false
    service-url:
      default-zone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka

spring:
  application:
    name: forex
  flyway:
    enabled: true
  sql:
    init:
      mode: always
  jpa:
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/exchange_value_source?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASS:admin}



