server:
  port: 8000

#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: forex
  flyway:
    enabled: true
  sql:
    init:
      mode: always
  jpa:
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3333/exchange_value_source?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin