apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: web-bc
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 10
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 80