apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyexchange
  labels:
    app: currencyexchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyexchange
  template:
    metadata:
      labels:
        app: currencyexchange
    spec:
      containers:
        - name: currencyexchange
          image: us-central1-docker.pkg.dev/titanium-deck-347513/forex-docker-repo/currencyexchange:latest
          ports:
            - containerPort: 8100
          env:
            - name: EUREKA_HOST
              value: eureka
            - name: EUREKA_PORT
              value: "8761"
            - name: FOREX_HOST
              value: forex
            - name: FOREX_PORT
              value: "8000"


