apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: forex-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 10
    healthyThreshold: 3
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /swagger-ui/index.html
    port: 80