version: '3.1'
services:
  db-forex-api:
    image: mysql
    restart: always
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exchange_value_source
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin