apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex
  labels:
    app: forex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forex
  template:
    metadata:
      labels:
        app: forex
    spec:
      containers:
        - name: forex
          image: us-central1-docker.pkg.dev/titanium-deck-347513/forex-docker-repo/forex:latest
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password


