apiVersion: apps/v1
kind: Deployment
metadata:
  name: webexchange
  labels:
    app: webexchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webexchange
  template:
    metadata:
      labels:
        app: webexchange
    spec:
      containers:
        - name: webexchange
          ports:
            - containerPort: 80
          env:
            - name: EUREKA_HOST
              value: eureka
            - name: EUREKA_PORT
              value: "8761"
            - name: CURRENCYEXCHANGE_HOST
              value: currencyexchange
            - name: CURRENCYEXCHANGE_PORT
              value: "8100"

